version: "3"

services:
  api_uds:
    build:
      context: ./api
    ports:
      - ${API_PORT}:80
    tty: true

  app_uds:
    build:
      context: ./app
    ports:
      - ${APP_PORT}:80
    tty: true
    depends_on:
      - api_uds
