version: "3"

services:
  api_uds:
    build:
      context: ./api
    command: "node dist/index.min.js"
    ports:
      - ${API_PORT}:80
    volumes:
      - ./api:/api
    tty: true

  app_uds:
    build:
      context: ./app
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./app:/app
    tty: true
    depends_on:
      - api_uds
